[project]
name = "chatbot_frontend"
version = "0.1"
dependencies = [
   "langchain-community==0.2.7",
   "langchain-openai==0.1.16",
   "neo4j==5.22.0",
   "streamlit==1.29.0"
]

[project.optional-dependencies]
dev = ["black"]
